package jp.knaka.cardmemo.storage
import androidx.room.withTransaction
import org.json.JSONArray
import org.json.JSONObject

data class RoomSnapshot(
 val transactions:List<TransactionEntity>,val sources:List<PaymentSourceEntity>,val categories:List<CategoryEntity>,val merchants:List<MerchantTemplateEntity>,val descriptions:List<DescriptionTemplateEntity>,
 val recurring:List<RecurringExpenseEntity>,val revisions:List<RecurringPriceRevisionEntity>,val statements:List<ImportedStatementEntity>,val entries:List<StatementEntryEntity>,val fingerprints:List<ImportedFingerprintEntity>,
 val matches:List<ReconciliationMatchEntity>,val rejected:List<RejectedReconciliationCandidateEntity>,val declarations:List<MonthlyPaymentSourceDeclarationEntity>,val locks:List<MonthlyLockEntity>,val budgets:List<MonthlyBudgetEntity>,val budgetSettings:AppBudgetSettingsEntity)

object RoomBackupAdapter{
 fun exportJson(db:RecoFiDatabase):JSONObject{val rev=db.recurringExpenses().loadRevisions().groupBy{it.recurringId};val entries=db.statements().loadEntries().groupBy{it.fileHash};return JSONObject().apply{
  put("transactions",JSONArray().apply{db.transactions().loadAll().forEach{t->put(JSONObject().put("id",t.id).put("amount",t.amount).put("category",t.category).put("merchant",t.merchant).put("description",t.description).put("usedAt",t.usedAt).put("recurringId",t.recurringId).put("paymentSourceId",t.paymentSourceId))}})
  put("paymentSources",JSONArray().apply{db.referenceData().loadPaymentSources().forEach{put(JSONObject().put("id",it.id).put("name",it.name).put("type",it.type).put("sortOrder",it.sortOrder))}})
  put("categories",JSONArray().apply{db.referenceData().loadCategories().forEach{put(JSONObject().put("name",it.name).put("sortOrder",it.sortOrder))}});put("merchantTemplates",JSONArray().apply{db.referenceData().loadMerchants().forEach{put(JSONObject().put("value",it.value).put("sortOrder",it.sortOrder))}});put("descriptionTemplates",JSONArray().apply{db.referenceData().loadDescriptions().forEach{put(JSONObject().put("value",it.value).put("sortOrder",it.sortOrder))}})
  put("recurringExpenses",JSONArray().apply{db.recurringExpenses().loadAll().forEach{e->put(JSONObject().put("id",e.id).put("amount",e.amount).put("category",e.category).put("merchant",e.merchant).put("description",e.description).put("billingDay",e.billingDay).put("startMonth",e.startMonth).put("contractDate",e.contractDate).put("paymentSourceId",e.paymentSourceId).put("intervalMonths",e.intervalMonths).put("endDate",e.endDate).put("priceRevisions",JSONArray().apply{rev[e.id].orEmpty().forEach{put(JSONObject().put("effectiveDate",it.effectiveDate).put("amount",it.amount))}}))}})
  put("importedStatements",JSONArray().apply{db.statements().loadStatements().forEach{s->put(JSONObject().put("fileHash",s.fileHash).put("statementMonth",s.statementMonth).put("paymentSourceId",s.paymentSourceId).put("fileName",s.fileName).put("entries",JSONArray().apply{entries[s.fileHash].orEmpty().forEach{put(JSONObject().put("id",it.id).put("rowOrder",it.rowOrder).put("date",it.date).put("amount",it.amount).put("merchant",it.merchant).put("rawText",it.rawText))}}))}})
  put("fingerprints",JSONArray(db.statements().loadFingerprints().map{it.fingerprint}));put("matches",JSONArray().apply{db.reconciliation().loadMatches().forEach{m->put(JSONObject().put("statementEntryId",m.statementEntryId).put("transactionId",m.transactionId).put("status",m.status).put("matchSource",m.matchSource).put("confidence",m.confidence).put("score",m.score).put("reasonCode",m.reasonCode).put("dayDifference",m.dayDifference).put("createdAt",m.createdAt).put("updatedAt",m.updatedAt).put("confirmedAt",m.confirmedAt))}});put("rejectedCandidates",JSONArray().apply{db.reconciliation().loadRejected().forEach{put(JSONObject().put("statementEntryId",it.statementEntryId).put("transactionId",it.transactionId).put("rejectedAt",it.rejectedAt))}});put("paymentSourceDeclarations",JSONArray().apply{db.reconciliation().loadDeclarations().forEach{put(JSONObject().put("month",it.month).put("paymentSourceId",it.paymentSourceId).put("status",it.status).put("updatedAt",it.updatedAt))}})
  put("locks",JSONArray(db.monthlyState().loadLocks().map{it.month}));put("budgets",JSONObject().apply{db.monthlyState().loadBudgets().forEach{put(it.month,it.amount)}});put("defaultMonthlyBudget",db.monthlyState().loadBudgetSettings()?.defaultMonthlyBudget?:0L)
 }}
 suspend fun replace(db:RecoFiDatabase,s:RoomSnapshot,beforeCommit:()->Unit={})=db.withTransaction{
  db.reconciliation().deleteRejected();db.reconciliation().deleteMatches();db.reconciliation().deleteDeclarations();db.transactions().deleteAll();db.statements().deleteEntries();db.statements().deleteStatements();db.statements().deleteFingerprints();db.monthlyState().deleteLocks();db.monthlyState().deleteBudgets();db.monthlyState().deleteBudgetSettings();db.referenceData().deleteMerchants();db.referenceData().deleteDescriptions();db.recurringExpenses().deleteRevisions();db.recurringExpenses().deleteAll();db.referenceData().deleteCategories();db.referenceData().deletePaymentSources()
  db.referenceData().upsertPaymentSources(s.sources);db.referenceData().upsertCategories(s.categories);db.referenceData().upsertMerchants(s.merchants);db.referenceData().upsertDescriptions(s.descriptions);db.recurringExpenses().upsertAll(s.recurring);db.recurringExpenses().upsertRevisions(s.revisions);db.transactions().upsertAll(s.transactions);db.statements().upsertStatements(s.statements);db.statements().upsertEntries(s.entries);db.statements().upsertFingerprints(s.fingerprints);db.reconciliation().upsertMatches(s.matches);s.rejected.forEach(db.reconciliation()::upsertRejected);db.reconciliation().upsertDeclarations(s.declarations);db.monthlyState().upsertLocks(s.locks);db.monthlyState().upsertBudgets(s.budgets);db.monthlyState().upsertBudgetSettings(s.budgetSettings);require(db.transactions().loadAll().size==s.transactions.size);beforeCommit()
 }
}
